apiVersion: apps/v1
kind: Deployment
metadata:
  name: Chaos
spec:
  replicas: 2
  selector:
    matchLabels:
      app: Chaos
  template:
    metadata:
      labels:
        app: Chaos
    spec:
      containers:
        - name: Chaos
          image: poseiden/Chaos
          env:
            - name: app_env
              value: "dev"
