server:
  port: 8080
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
#    password: password
    platform: org.hibernate.dialect.H2Dialect
  jpa:
    hibernate:
      ddl-auto: create-drop

